### ISSUE TITLE
Update to histogram to enhance visibility and overall usability

### ISSUE THREAD

**Issue by todd-prior** [darktable-org/darktable#6227]
**Is your feature request related to a problem? Please describe.**
I find the histogram esp the parade and wave views very hard to make use of due to size and color scheme

**Describe the solution you'd like**
Having some recent discussions with @dtorop around possible changes I provided several examples from the implementation used in Davinci Resolve. I find those to be superior for visibility and usability. Examples and discussion are found in PR 6135 https://github.com/darktable-org/darktable/pull/6135 by way of screenshots and a couple of video links

**Alternatives**
1> Ability to increase or decrease brightness of the displayed histogram or waveform and or the display grid...see 
2 The ability to potentially un-dock and or enlarge the display to a greater extent than is currently possible up to and including the ability to un-dock and display on a second monitor or the main screen as can be done with the preview window
3. Some indication of the current data being shown by the histogram so that it is clear 
4. The ability to display the color picker data to the histogram can be checked and displayed but as soon as you enable a module the histogram reverts to the pipeline for the full image. I would be useful to be able to select a range with the picker say a shadow area and have the histogram retain that data and display so for example some color balancing could be done on shadow areas or any other area selected by the picker..this might extend to masked area ie it might be nice to see the histogram for the currently selected mask...the potential of this is shown in a provided video where a color chart is broken down and waveforms are used to set WB and the color and saturation of primary colors from a color chart.....for context and a better explanation see my comments with @dtorop  PR 6135 for specifics as mentioned Examples of brightness controls and representative output can be seen here https://mcmasteru365-my.sharepoint.com/:v:/g/personal/priort_mcmaster_ca/EUagu0gTFApBl6FZ4t92tkUBVqJKfPupDEuG3v-g8_TQwg?e=tcofVr as well https://wipster.io/blog-for-creative-teams-who-want-better-collaboration-tools/scope-features-davinci-resolve    

**Additional context**
See PR 6135....

**Comment by johnny-bit** [comment]
@todd-prior - given recent changes as of [today's current master], what more changes would you see?
@dtorop - given your comment in https://github.com/darktable-org/darktable/issues/3005#issuecomment-843444984 i assume that this FR is on your scope? ... I mean radar :wink:

**Comment by todd-prior** [comment]
I’ll go in and check …for me the big own was that you could not keep the vectorscope associated with a selection. It could be initially but then any further action caused it to jump to the full image…so for example if you were trying to tweak skin tones it is not possible to select a region of the skin and monitor a correction even with restrict to selection set.

If this can be corrected I am happy with the vectorscope as it exists. One last issue for me is placement of the scopes. I have a large monitor that is wide and so the scope are well off to the side and up in the corner so if I have any light on there can be some glare and I have to physically move my head over to line up head on to look at the scopes…If ever they could be popped out or moved or displayed on a second monitor that would be huge…..

**Comment by dtorop** [comment]
@johnny-bit Happy to have this in, er, scope... Some notes:

> 1. Ability to increase or decrease brightness of the displayed histogram or waveform and or the display grid

I still would like to think we can just get this right so it's universally legible rather than another control. 3b35cad092c05b315f63c040a85ecf36f862cbb9 already improved RGB parade a bit. Here's one pitch to make the graphs more legible:

- Histogram: Draw a border line on the top, as will as a filled-in line below. Border line is something like 50% of the channel color plus 50% white (e.g. red outline is 1,0.5,0.5).
- RGB parade and vectorscope: Draw the graph twice, adding the results. Once in the graph color, once in white, each time with alpha controlled by count of points in bin. This will emphasize "volume" of more frequent graph points by increasing lightness & decreasing chroma. (I don't think this will work for waveform, as we still want to keep the R + G + B = white behavior, and waveform is already pretty legible.)
- Waveform, RGB parade, and vectorscope: Make the most graph "volume" not be scaled by a fixed brightness, but normalized such that the most frequently seen graph points are 100%.
- Vectorscope: Do color saturation/alpha work in RGB rather than in CIELUV/JzAzBz, which should give better light/dark control.

> 2. The ability to potentially un-dock and or enlarge the display to a greater extent than is currently possible up to and including the ability to un-dock and display on a second monitor or the main screen as can be done with the preview window

I'm not sure what to do about this. It would probably be possible to make something akin to the 2nd darkroom image window: a pop-out panel which would have scope data. Or to add a scope option to the 2nd darkroom window (image + scope, or maybe image or scope). I think this would need to be a larger discussion: Are there other needs for pop-out panels in darkroom view? This would be a really big UI intervention.

Another question is whether the scope should even be in the top-right or if there are other useful homes for it, e.g. the left panel. This would give more space for iops on the right. (I find myself hardly ever looking at the navigation on top left, and generally hide the left panel for focused work. I do often wish for more vertical space on the right panel.)

And should there be an option to show multiple scopes at once? This ends up all being a big can of worms and at the best would require good judgment and consensus.

> 3. Some indication of the current data being shown by the histogram so that it is clear

I'm not sure what this means. Does this mean giving quantitative readouts?

> 4. The ability to display the color picker data to the histogram can be checked and displayed but as soon as you enable a module the histogram reverts to the pipeline for the full image.

I think this is the same as #8680, which I've also forgotten about but needs attention. I'm happy to look into this. As I wrote there, I think this is baked into pixelpipe, and may be intentional, but not ideal.

**Comment by todd-prior** [comment]
@dtorop  Dan thanks for your detailed feedback. It sounds like you have some ideas to address point 1. My only comment there is that you can't account for what happens to a great looking scope when it hits a variety of monitors set a various levels of brightness quality and color accuracy so that may be one reason to allow some adjustment if possible... Just a thought on point 1
Point two was a wish list thing for me and I suggested the preview window because I was thinking as you suggested that there could be some setting for either scopes or second preview something like that within the current way darktable works.

Not sure about point 3. You do have a dot showing on the vectorscope to indicate the current global picker. I am not sure I would need something on the histogram.

And 4 as I said functions initially but if you wanted to select a region of interest and then make any adjustment you lose this so for example I select some skin or a rock or something and get a scope of that selection. Now I go to try and say use rgb curves to work on that and the scope redraws instantly to the full image 

See here a rosy cheek selection. 

![image](https://user-images.githubusercontent.com/44409419/118743087-aa901b80-b81f-11eb-9c20-bb92355f417d.png)

and then I go to adjust the red a bit....

and boom I now have this to work with..

![image](https://user-images.githubusercontent.com/44409419/118743171-d4e1d900-b81f-11eb-96b9-22ea859e180b.png)


THe vectorscope does the same thing.

So there needs to be a way without cropping in on a region to do this. Right now the best that can be done it make an adjustment then hit ctrl + global color pipette again but without a live display its not worth it its better to crop and then turn it off when you are done. I guess having a quick crop to selection feature would be a way around it if that is not hard to implement but I feel like that is a work around.

Thanks for all your hard work......

**Comment by dtorop** [comment]
To update for the no-issue-activity bot:

- [ ] There's work afoot to move the histogram, first step is #9640 
- [X] #9052 being merged should help with waveform and rgb parade visibility
- [ ] I'm still working on a similar appearance update for vectorscope (#9209)
- [ ] I'm working on code to fix colorpicker restrict to histogram (#5689)

**Comment by dtorop** [comment]
It may be possible to close this FR?

- It is now possible to move the histogram to the left sidebar (#9640, #10293)
- Updates to waveform, rgb parade, and vectorscope appearance merged (#9053, #9209)
- Restrict to scope to selection fix merged (#9835)

I know there's still work to be done, but closing this as a meta-issue could leave room for particular work in the future...

**Comment by todd-prior** [comment]
Happy for it to be closed...


Get Outlook for Android
