### ISSUE TITLE
tasks for c&r rewrite

### ISSUE THREAD

**Issue by AlicVB** [darktable-org/darktable#8834]
This is a proposal for a replacement of crop & rotate module (see #6736)
the idea is to define a reorganization / additions of modules in order to achieve that.

We have some points to take into account : 
1. cropping and rotation are key features that will be used in 90% of edits. So they should be well implemented, safe and performant.
2. we should avoid as much as possible multiple interpolations for quality reasons. That's why the goal would be here to avoid if possible the creation of a new interpolation module... note : crop & flip don't interpolate
3. like for all modules, we'll of course keep in any cases actual c&r to ensure backward compatibility. We can either deprecate it once all the replacement is done, either keep it with new code path limited to the new features (and only show old things for olders edits)
4. That will change the area where all this features are located. We must be careful that cropping and rotation can be found *very* easily. We now have the QAP for that... do we need some sort a even more obvious way ?

You'll find above, feature by feature, what need to be done (this is a proposal, remember) : 

### guidelines : 
(Independent of C&R rewrite)
- moved outside modules code (iirc that's already partially the case)
- we can have a "global" btn to show/hide/configure them and global stata saved (solve #8582)
- same btn can go inside modules who need them and state saved per modules (where module state > global state)
- all modules with distortion settings can potentially be interested by this feature

### cropping
(Independent of C&R rewrite)
work started by @jenshannoschwalm in #8833 seems that I will take over :)
- there's no interpolation involved so no real perf issues (to be confirmed) and no "quality" issues
- this can happen late in the pipe so pixels outside the crop area can be used by modules for some stuff (borders artefacts, retouch, ...)
- can expose some proxy function so modules can eventually change the crop values themself (autocrop, ...) Of course we have to put some safety to avoid dropping user defined cropping...

### keystone
=> lensfun proposal (my preference)
- lensfun already has this inside it's api, but with the needed "distance" parameter.
- lenscorrection currently doesn't have any gui stuff, so adding some won't put too much mess...
- keystone correction is not really a "key" feature, so even if dt is built without lensfun, that won't be a problem imho
- lensfun will do the interpolation in one step, so no double-interpolation
- but lensfun can be a little slower than other modules esp. by the lack of opencl

=> perspective proposal
- we can imagine 2 mode for this module : automatic (current) and manual (keystone)
- all interpolation in one step (no new interpolation added)
- possibly opencl code
- we make ashift more complex (no so much if we clearly separate the 2 modes inside the code)
- if we want to add the "distance" feature... I'll need some help (see the actual computations in c&r if you want to see the "problem")

=> standalone proposal
- self encapsulated, so code will be simpler to debug, fix, ...
- opencl code
- if we want to add the "distance" feature... I'll need some help (see the actual computations in c&r if you want to see the "problem")
- add another interpolation step (not the better quality wise)

### rotation
this is a critical feature, so we need to ensure that it will be safe/efficient/...

=> lensfun proposal
- all interpolations in 1 step
- not too much gui stuff actually in lenscorrection...
- lensfun is optional so we need a fallback ! (one of the other proposal)
- complex module gui for the "usual" just rotate stuff

=> perspective proposal
- already here, so we "just" have the right click stuff to add
- opencl
- complex module gui for the "usual" just rotate stuff

=> standalone proposal
- extremely simple module gui
- add another interpolation step (not the better quality wise)

=> "fake" module proposal (my preference)
- first setting : which module to use (lens or ashift)
- imho default to lens is better as more widely used (if present of course)
- lens and perspective expose proxy functions to get/set the rotation
- extremely simple module gui

### flip
- no interpolation (afaik)
- could be added in the orientation module as imho it's mainly a "sensor correction" thing (that won't prevent to use it as creative)
- iirc, this module already has this for some sort a sensor, so it would only be some gui to add

### position in the pipeline
It is important (see #8634) for quality and workflow.
1. for cropping, I think we should do it as late as possible, after all modules that may need pixels outside crop area (borders artifact, ...) The only drawback would be perfs drop for heavily cropped images, but that's imho a corner case.
2. For interpolations stuff, I would also say that they should go late in the pipe so modules don't inherits from interpolated datas (@jenshannoschwalm ), but I know that there's other positions on this (@aurelienpierre )
3. retouch should go after distortions, as @aurelienpierre explain in #8634 , in order to ensure that images structures are correctly aligned when we do the source copying

task summary : 

- [x] guidelines (done in #8891 )
- [x] cropping module (done in #8838)
- [x] keystone (done in #9456)
- [x] rotation (done in #9456)
- [x] flip (done in #9327)

**Comment by aurelienpierre** [comment]
I started to look into turning `ashift.c` manual, it requires some maths adjustments but we can essentially re-use the pixel code as-is and only add a manual GUI. I much prefer having one single module to handle perspective.

Hacking perspective into lens distortion seems brittle and dangerous, since it will make debugging much harder if they come in pack. Also, it will be redundant with whatever fallback it chosen.

> For interpolations stuff, I would also say that they should go late in the pipe so modules don't inherits from interpolated datas (@jenshannoschwalm ), but I know that there's other positions on this (@aurelienpierre ).

This is a rotation done in linear space : https://d1ehq6mh87pjr.cloudfront.net/wp-content/uploads/sites/8/2021/02/etoile-krita-pivote-gimp.jpg

This is a rotation done in non-linear space : https://d1ehq6mh87pjr.cloudfront.net/wp-content/uploads/sites/8/2021/02/etoile-krita-tourne-non-lineaire.jpg

Draw your own conclusions…

**Comment by AlicVB** [comment]
@aurelienpierre : do you think you'll be able to handle the math part of integrating keystone inside ashift ? (integration of the "famous" distance parameter would be great too, but not crucial as not implement atm)

> Hacking perspective into lens distortion seems brittle and dangerous, since it will make debugging much harder if they come in pack

well, I've just proposed that because lensfun has *exactly* this feature in it's api (iirc, they have added it on the model of what is done in dt) but if someone is able to do that directly in dt :)

For the interpolation, I was sure you'll have some insight for us :) So we should keep interpolation stuff in the linear part, right ? where would you put them ? the simplest is to not move them at all :)

**Comment by aurelienpierre** [comment]
> @aurelienpierre : do you think you'll be able to handle the math part of integrating keystone inside ashift ? (integration of the "famous" distance parameter would be great too, but not crucial as not implement atm)

With enough sleep, coffee and time, yes. That's good old linear algebra.

> So we should keep interpolation stuff in the linear part, right ? where would you put them ? the simplest is to not move them at all :)

Yes. Their current place is, however, not suited for JPEG/PNG/etc. since their gamma/OETF gets decoded in input color profile. They could go as late as just after color calibration, but no later. Also the high-pass/contrast EQ modules need to go after interpolations.

**Comment by parafin** [comment]
> * lensfun is optional so we need a fallback !

Or make lensfun a hard dependency. I don't really get why one of the iops is optional in dt...

**Comment by ralfbrown** [comment]
My opinions/preferences on where to move the c&r functionalites:

- **crop**: new module dedicated solely to cropping.  Should be placed after any modules that might take pixels from outside the crop area (e.g. liquify, retouch, spot removal, and possibly tone equalizer [mask will differ before/after crop]), preferably immediately after the last such module for best performance.
- **flip**: obviously belongs in the orientation iop
- **rotate**: use the existing rotation in perspective correction (and put that slider in the QAP in place of the c&r angle slider).  Add "rotate" and "rotation" as search terms for p.c. if not already there.
- **keystone**: add to p.c.

**Comment by elstoc** [comment]
> rotate: use the existing rotation in perspective correction (and put that slider in the QAP in place of the c&r angle slider). Add "rotate" and "rotation" as search terms for p.c. if not already there.

We still need some sort of global way to apply rotations with the mouse as well (the click+drag method) - preferably without having to open a module. Technically, putting rotate in perspective correction might be correct, but rotation might be the only slider people ever use in it, so a rename might be in order.

**Comment by AlicVB** [comment]
if we go that way (using perspective correction for keystone and rotation) we have to be very careful to not produce another unmaintainable monster...
How I see it : 
- a 3 tab interface (rotation, automatic perspective, manual keystone)
- each tab has it's own gui stuff, independent from each other
- for the internals, only keystone will add some complexity.

problems : 
- automatic perspective will change a slider in another tab (the rotation one) is that a problem for users ?
- how to name that module then (we should advertise rotation first imho) ?

**Comment by elstoc** [comment]
Regarding the UI, I'd say that rotate is a common enough option that it should be available across the tabs. On the other hand, do we expect a user to want to do both manual and automatic correction at the same time? Or should they be mutually exclusive operations (in which case we should have a single tab with a manual/auto mode)?

Regarding naming I think the choices are a list of words or a single word that kind of summarises all three pieces of functionality. 

Keystone is basically a manual perspective correction so I don't think we need to call that out explicitly. So "rotate & perspective" might be ok.

If we want a single word that kind of incorporates all three, would something like "viewpoint" be too vague? Would "distort" be too generic?

**Comment by AlicVB** [comment]
@elstoc : you're right about manual/automatic mode : both will set the same settings, so they are mutually exclusive...
Another proposal : 
3 sections : 
- general : rotation (x2) autocrop guides
- perspective : manual/auto combo which define the widgets to show
- settings (under an expander) : with the keystone/shear/lens widgets (they will be set directly from the perspective section, they are just here to refine or do completely manual edit)

name : imho "rotate & perspective" can be a good choice. personally I prefer your other proposal, but they don't advertise the "rotate" part enough, and that's a crucial point for this feature imho...

note : I still want to look at the code and verify that we have something very robust and easy to debug atm... This is crucial for such important feature as rotation !

**Comment by difrkaguilar** [comment]
I just read this post and I had made an visual approach to the orientation module.
 And posted in Pixls.us

https://discuss.pixls.us/t/flip-images-horizontally-and-or-vertically/25330

This is only an idea regarding the GUI
Thanks to all of you for your efforts to create this amazing app.

**Comment by elstoc** [comment]
This is available in crop & rotate already and will of course need to be moved somewhere else as part of the rewrite.

**Comment by difrkaguilar** [comment]
I don´t know if is possible/useful make the flip option independent of the modules, something users can enable/disable at any moment without commitment with the workflow, and as I explain in the post this changes not be permanent, if user like to make it permanent could be an option for it in the export module like the others parameters (style, intent, profile, shore masks, etc).

**Comment by ralfbrown** [comment]
The nondestructive nature already means you can toggle any setting as often as you want "without commitment".  But anything that needs to be explicitly enabled during export to ensure that it actually is committed is an extra click which is prone to being forgotten (which leads to even more clicks as you export the image(s) a second time).

Aside from informational overlays, what you see while editing should be what is exported unless you add a style during export.

**Comment by difrkaguilar** [comment]
Well, then will be a WYSIWYG and not present in the export module.

**Comment by elstoc** [comment]
You can always use the quick access panel if you want to consolidate some often-used controls in one place.

**Comment by AlicVB** [comment]
This should now be completely done in master. To resume for the record : 
- rotation and keystoning are now handled in the "perspective" module (renamed "rotation & perspective")
- flip is handled by the "orientation" module
- crop is handled by the new "crop" module

So we should be equals in term of features. Of course this will need some workflow adaptations...

As seen with @TurboGit , next step is the deprecation of the c&r module. This will happen soon, once we have some more field testing, especially for the changes in the "rotation & perspective" module. (as always, deprecating a module doesn't means we remove it, just that it won't be develop further and should not be used for new work)

I let this issue open until the final c&r deprecation

**Comment by Nilvus** [comment]
@AlicVB: reading your last comment, this issue could now be closed as c&r is now deprecated. I so close.
